-- Schema placeholder. Revamp branch: tables will be re-derived from the new
-- entity class diagrams as Sprint 1 entities are rebuilt. Kept as an empty
-- script so persistence/db.py's init_db() and tests/conftest.py's fresh_db
-- fixture continue to function (executescript on an empty string is a no-op).
