"""GenerateReportPage <<Boundary>> — Sprint 4 US-41 / US-42 / US-43.

All three diagrams name the boundary class `GenerateReportPage`.
Implementation hosts one page with an internal radio for daily / weekly
/ monthly; each routes to the diagram-defined controller.

The PM picks one date; the boundary derives the (start, end) window
from the chosen report type — daily = the date itself; weekly =
Monday→Sunday of that ISO week; monthly = 1st→last day of that month.
The diagram-defined controllers + entity methods still take
`(startDate, endDate, platformManagerId)` so the contract is unchanged
— this is a boundary-only UX simplification.

`platform_manager_id` is sourced from the logged-in user — the diagram
method signatures omit it but the entity declares it as an attribute,
logged in docs/diagram_typos.md as a Sprint 4 typo.
"""
from __future__ import annotations

from calendar import monthrange
from datetime import date, timedelta

import streamlit as st

from controller.generate_daily_report_controller import (
    GenerateDailyReportController,
)
from controller.generate_monthly_report_controller import (
    GenerateMonthlyReportController,
)
from controller.generate_weekly_report_controller import (
    GenerateWeeklyReportController,
)


class GenerateReportPage:
    def render(self) -> None:
        st.header("Generate Report")

        if "user" not in st.session_state:
            st.warning("Please log in first.")
            return

        pm_account_id = st.session_state["user"].account_id

        with st.form("generate_report_form"):
            report_type = st.radio(
                "Report type",
                ("daily", "weekly", "monthly"),
                horizontal=True,
            )
            picked = st.date_input("Report date", value=date.today())
            submitted = st.form_submit_button("Generate")

        if not submitted:
            return

        start_date, end_date = self.window_for(report_type, picked)

        if report_type == "daily":
            report = (
                GenerateDailyReportController().generate_daily_report(
                    start_date=start_date,
                    end_date=end_date,
                    platform_manager_id=pm_account_id,
                )
            )
        elif report_type == "weekly":
            report = (
                GenerateWeeklyReportController().generate_weekly_report(
                    start_date=start_date,
                    end_date=end_date,
                    platform_manager_id=pm_account_id,
                )
            )
        else:
            report = (
                GenerateMonthlyReportController().generate_monthly_report(
                    start_date=start_date,
                    end_date=end_date,
                    platform_manager_id=pm_account_id,
                )
            )

        self.display_report(report)

    @staticmethod
    def window_for(report_type: str, picked: date) -> tuple[date, date]:
        """Derive (start_date, end_date) from the PM's single picked date.

        - daily: same day
        - weekly: Monday→Sunday of the ISO week containing `picked`
        - monthly: 1st→last day of the month containing `picked`
        """
        if report_type == "daily":
            return picked, picked
        if report_type == "weekly":
            # `weekday()` returns 0=Mon … 6=Sun.
            monday = picked - timedelta(days=picked.weekday())
            sunday = monday + timedelta(days=6)
            return monday, sunday
        if report_type == "monthly":
            first = picked.replace(day=1)
            last_day = monthrange(picked.year, picked.month)[1]
            last = picked.replace(day=last_day)
            return first, last
        raise ValueError(f"Unknown report_type: {report_type!r}")

    @staticmethod
    def display_report(report) -> None:
        st.subheader(f"{report.report_type.title()} report — {report.report_id}")
        st.write(
            f"**Window:** {report.start_date.isoformat()} → "
            f"{report.end_date.isoformat()}"
        )
        st.write(f"**Generated at:** {report.generated_at.isoformat()}")
        st.write(f"**Generated by:** {report.platform_manager_id}")
        st.divider()
        cols = st.columns(3)
        cols[0].metric("Donations (count)", report.total_donation_count)
        cols[1].metric(
            "Donation amount", f"${report.total_donation_amount}"
        )
        cols[2].metric("Activities", report.total_activity_count)
        cols2 = st.columns(2)
        cols2[0].metric("Fundraisers", report.total_fundraiser_count)
        cols2[1].metric("Donees", report.total_donee_count)
